version: '2'

services:
  base:
    environment:
      - SVNUSER=svnusername
      - SVNPASS=svnpassword
      - MYSQL_ROOT_PASSWORD=newznab
      - MYSQL_DATABASE=newznab
      - MYSQL_USER=newznab
      - MYSQL_PASSWORD=newznab
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - APACHE_LOG_DIR=/var/log/apache2
      - APACHE_LOCK_DIR=/var/lock/apache2
      - APACHE_PID_FILE=/var/run/apache2.pid
      - NNTP_USERNAME=
      - NNTP_PASS=
      - NNTP_SERVER=
      - NNTP_PORT=443
      - NNTP_SSL=true
